name = "QuantumAnnealing"
uuid = "4832667a-bab9-40a8-88f6-be9efce3ea89"
authors = ["Zach Morrell, Carleton Coffrin, Marc Vuffray"]
repo = "https://github.com/lanl-ansi/QuantumAnnealing.jl"
version = "0.2.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSV = "~0.10, ~0.9, ~0.8, ~0.7"
OrdinaryDiffEq = "~6, ~5"
JSON = "~0.21, ~0.20, ~0.19, ~0.18"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"


[targets]
test = ["Test", "Random"]
